
default_twitter: &default_twitter
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  twitter_access_token: "Access token"
  twitter_access_token_secret: "Access token secret"
  twitter_callback_url: <%= ENV["TWITTER_CALLBACK_URL"] %>

development:
  secret_key_base: a920118962e4438908f03e6bcc3a3e6327e461649c25eb58a768d7efa7a8b72e2346c8af695f4848d3eef89289a9634a839ad4de30b84b71cb6b16cf2d7de966
  <<: *default_twitter

test:
  secret_key_base: 55bb0d6435a58eb40ad007a11cb6f290f98c695554f5698aeea60aa25e8714c7d332541741e1c08a882c33907812f3ae096c963c6abeb90b3095a4846a734a6a
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
